#!/bin/bash
set -euo pipefail
PATH=`pwd`/toolchains/gcc-13-riscv/imported \
LD_LIBRARY_PATH=external/fedora39-system-libs \
  external/gcc-13-riscv64-toolchains/libexec/gcc/riscv64-unknown-linux-gnu/12.2.0/collect2 "$@"
