#!/bin/bash
set -euo pipefail
PATH=`pwd`/toolchains/gcc-13-riscv/imported \
LD_LIBRARY_PATH=external/fedora38-system-libs \
  external/gcc-13-riscv64-toolchains/bin/riscv64-unknown-linux-gnu-objcopy "$@"
