load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# custom risc-v 64 bit toolchains
http_archive(
    name = "gcc-12-riscv64-toolchains",
    urls = ["file:///opt/bazel/risc64_linux_gnu-12.tar.xz"],
    build_file = "//:gcc-12-riscv64-toolchains.BUILD",
    sha256 = "58bc005f5cbc8b6ef2e52aa29c013d7fe1777708103a77767260a3f3e2bf8542",
)
http_archive(
    name = "gcc-13-riscv64-toolchains",
    urls = ["file:///opt/bazel/risc64_linux_gnu-13.tar.xz"],
    build_file = "//:gcc-13-riscv64-toolchains.BUILD",
    sha256 = "8022d3e61f7ab709379284418799cbddea47dc90f77e80eaf3df2706b513d4c8",
)

# partial gcc-14 risc-v 64 bit toolchain without libc or C++
http_archive(
    name = "gcc-14-riscv64-toolchains",
    urls = ["file:///opt/bazel/risc64_linux_gnu-14.tar.xz"],
    build_file = "//:gcc-14-riscv64-toolchains.BUILD",
    sha256 = "703f4e7e2ac9b0fdbab95d2ac99992e5a9692f5486de7c4cf97d76f21b81de80",
)

# system libraries used by toolchain build system
# We built the custom toolchain on a fedora x86_64 platform, so we need some
# fedora x86_64 sharable system libraries to execute.
http_archive(
    name = "fedora39-system-libs",
    urls = ["file:///opt/bazel/fedora39_system_libs.tar.xz"],
    build_file = "//:fedora39-system-libs.BUILD",
    sha256 = "fe91415b05bb902964f05f7986683b84c70338bf484f23d05f7e8d4096949d1b",
)

register_toolchains(
    # a separate Bazel project independent of /opt/riscv,
    # currently based on gcc-13-riscv64-toolchains
    "//toolchains:riscv64-default",
    # an experimental and partial toolchain based on gcc-14-riscv64-toolchains
    "//toolchains:riscv64-next",
    # a local x86_64 toolchain based on whatever the host provides
    "//toolchains:x86_64_local_host",
)
