load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# stable gcc-14 risc-v 64 bit toolchain
http_archive(
    name = "gcc-13-riscv64-toolchains",
    urls = ["file:///opt/bazel/risc64_linux_gnu-13.tar.xz"],
    build_file = "//:gcc-13-riscv64-toolchains.BUILD",
    sha256 = "8022d3e61f7ab709379284418799cbddea47dc90f77e80eaf3df2706b513d4c8",
)

# developmental (unreleased) gcc-14 risc-v 64 bit toolchain
http_archive(
    name = "gcc-14-riscv64-toolchains",
    urls = ["file:///opt/bazel/risc64_linux_gcc-14.0.1.tar.xz"],
    build_file = "//:gcc-14-riscv64-toolchains.BUILD",
    sha256 = "b5831f2bd837d6f8e3f9cd04b55695ca3e89ecf2387d6b448215a84ba4708508",
)

# developmental (unreleased) gcc-14 x86-64 bit toolchain used in local unit tests
http_archive(
    name = "gcc-14-x86_64-toolchains",
    urls = ["file:///opt/bazel/x86_64_linux_gnu-14.tar.xz"],
    build_file = "//:gcc-14-x86_64-toolchains.BUILD",
    sha256 = "df535d99965dc280a83b73f5c3af17c60c66779f107937954330139537dc7072",
)

# system libraries used by toolchain build system
# We built the custom toolchain on a fedora x86_64 platform, so we need some
# fedora x86_64 sharable system libraries to execute.
http_archive(
    name = "fedora39-system-libs",
    urls = ["file:///opt/bazel/fedora39_system_libs.tar.xz"],
    build_file = "//:fedora39-system-libs.BUILD",
    sha256 = "fe91415b05bb902964f05f7986683b84c70338bf484f23d05f7e8d4096949d1b",
)

# whisper.cpp is an open source voice-to-text inference app built on Meta's LLaMA model.
# It is a useful exemplar of autovectorization of ML code with some examples of hand-coded
# riscv intrinsics.
http_archive(
    name = "whisper_cpp",
    urls = ["https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.4.tar.gz"],
    strip_prefix = "whisper.cpp-1.5.4/",
    build_file = "//:whisper-cpp.BUILD",
    sha256 = "06eed84de310fdf5408527e41e863ac3b80b8603576ba0521177464b1b341a3a"
)

register_toolchains(
    # a separate Bazel project independent of /opt/riscv,
    # currently based on gcc-13-riscv64-toolchains
    "//toolchains:riscv64-default",
    # a toolchain based on a snapshot of gcc-14-riscv64-toolchains
    "//toolchains:riscv64-next",
    # a toolchain loaded with supported customizations
    "//toolchains:riscv64-custom",
    # a non-hermetic local toolchain used in debugging the Bazel sandbox
    "//toolchains:riscv64-local",
    # an x86_64 toolchain for unit testing, hopefully aligned with riscv64-next
    "//toolchains:x86_64-next",
)
