#!/bin/bash
set -euo pipefail
PATH=`pwd`/toolchains/gcc-14-riscv/imported \
LD_LIBRARY_PATH=external/fedora39-system-libs:/lib64 \
  external/gcc-14-riscv64-toolchains/bin/riscv64-unknown-linux-gnu-objcopy "$@"
