#!/bin/bash
set -euo pipefail
PATH=`pwd`/toolchains/gcc-14-riscv/imported \
LD_LIBRARY_PATH=external/fedora38-system-libs\
  external/gcc-14-riscv64-toolchains/bin/riscv64-unknown-linux-gnu-ld.bfd "$@"
