load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# gcc-14 x86_64 toolchain from snapshot gcc-14 and glibc development heads
http_archive(
    name = "gcc-14-x86_64-toolchains",
    urls = ["file:///opt/bazel/x86_64_linux_gnu-14.tar.xz"],
    build_file = "//:gcc-14-x86_64-toolchains.BUILD",
    sha256 = "df535d99965dc280a83b73f5c3af17c60c66779f107937954330139537dc7072",
)

# system libraries used by toolchain build system
# We built the custom toolchain on a fedora x86_64 platform, so we need some
# fedora x86_64 sharable system libraries to execute.
http_archive(
    name = "fedora39-system-libs",
    urls = ["file:///opt/bazel/fedora39_system_libs.tar.xz"],
    build_file = "//:fedora39-system-libs.BUILD",
    sha256 = "fe91415b05bb902964f05f7986683b84c70338bf484f23d05f7e8d4096949d1b",
)

http_archive(
    name = "whisper_cpp",
    urls = ["https://github.com/ggerganov/whisper.cpp/archive/refs/tags/v1.5.4.tar.gz"],
    strip_prefix = "whisper.cpp-1.5.4/",
    build_file = "//:whisper-cpp.BUILD",
    sha256 = "06eed84de310fdf5408527e41e863ac3b80b8603576ba0521177464b1b341a3a"
)

register_toolchains(
    # an experimental toolchain based on gcc-14 and a 64 bit Fedora-39 system root
    "//toolchains:x86_64_default",
)
